spring:
  datasource:
    url: jdbc:h2:mem:identity;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
    driver-class-name: org.h2.Driver
    username: sa
    password: ''
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  main:
    banner-mode: "off"
logging:
  level:
    root: info
management:
  endpoints:
    web:
      exposure:
        include: health,info
identity:
  tokens:
    issuer: https://identity.foodify.local
    audience: foodify-platform
    scope: openid profile email
    token-type: Bearer
