spring:
  application:
    name: delivery-service
  datasource:
    url: ${DELIVERY_DATABASE_URL:jdbc:postgresql://localhost:5432/delivery_service}
    username: ${DELIVERY_DATABASE_USERNAME:delivery_service}
    password: ${DELIVERY_DATABASE_PASSWORD:delivery_service}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: false
  cloud:
    discovery:
      enabled: ${SPRING_CLOUD_DISCOVERY_ENABLED:false}
  main:
    banner-mode: "off"

server:
  port: ${DELIVERY_SERVICE_PORT:8082}

logging:
  level:
    root: info

management:
  endpoints:
    web:
      exposure:
        include: health,info
  tracing:
    enabled: ${MANAGEMENT_TRACING_ENABLED:false}
    sampling:
      probability: 1.0
  otlp:
    tracing:
      endpoint: ${OTEL_EXPORTER_OTLP_ENDPOINT:http://localhost:4317}

eureka:
  client:
    enabled: ${EUREKA_CLIENT_ENABLED:false}
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka}
    register-with-eureka: ${EUREKA_REGISTER_WITH_EUREKA:true}
    fetch-registry: ${EUREKA_FETCH_REGISTRY:true}
  instance:
    prefer-ip-address: true

delivery:
  driver-location:
    cache-ttl: ${DELIVERY_DRIVER_LOCATION_TTL:PT5M}
