package com.foodify.server.modules.notifications.domain;

public enum NotificationType {
    ORDER_DRIVER_NEW_ORDER,
    ORDER_CLIENT_ORDER_ACCEPTED,
    ORDER_DRIVER_ASSIGNED,
    ORDER_DRIVER_ORDER_READY,
    ORDER_CLIENT_ORDER_READY,
    ORDER_CLIENT_ORDER_EN_ROUTE,
    ORDER_CLIENT_ORDER_DELIVERED,
    ORDER_CLIENT_ORDER_CANCELED,
    ORDER_CLIENT_ORDER_REJECTED
}
