spring:
  application:
    name: image-service

server:
  port: ${SERVER_PORT:8082}

management:
  endpoints:
    web:
      exposure:
        include: health,info

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka}
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true

images:
  location: ${IMAGES_LOCATION:uploads}
  public-base-url: ${IMAGES_PUBLIC_BASE_URL:}
